### ISSUE TITLE
Scala version 2.13 not supported in Maven.

### ISSUE THREAD

**Issue by basarama** [jliszka/probability-monad#19]
If possible could we get this package published for scala 2.13? This package has been a great help for me trying to write tests for my code and it'd be awesome if we could get 2.13 support so I can upgrade other packages I rely on.

**Comment by jliszka** [comment]
Sure! I'll work on it tonight. Looks like there are a few breaking changes between 2.12 and 2.13... parallel collections, procedure syntax.

**Comment by jliszka** [comment]
I just published 1.0.4 for scala 2.12 and 2.13. Let me know if that works!

1.0.4 has no substantial changes besides 2.13 compatibility, but that involves an extra dependency that might get pulled in.
